### PR TITLE
Update build.gradle

### PR DESCRIPTION
**Pull request by aleksoft1**
Need update this dependencies in every task

### CODE REVIEW

**Comment by aleksoft1** [comment]
I signed it!

**Comment by maryx** [comment]
Hi @aleksoft1, I'm not sure it's necessary to update the Android Gradle plugin version and we want to maintain compatibility with lower versions of Gradle. At 3.0.1, the build should work with Gradle version 4.1+ (https://developer.android.com/studio/releases/gradle-plugin). If we update to 3.2.1, it will no longer be compatible with versions below 4.6.

Are you able to build the app with the current code (3.0.1)?

**Comment by aleksoft1** [comment]
> Hi @aleksoft1, I'm not sure it's necessary to update the Android Gradle plugin version and we want to maintain compatibility with lower versions of Gradle. At 3.0.1, the build should work with Gradle version 4.1+ (https://developer.android.com/studio/releases/gradle-plugin). If we update to 3.2.1, it will no longer be compatible with versions below 4.6.
> 
> Are you able to build the app with the current code (3.0.1)?

No, I can't. This is the output from the console if I try with 3.0.1

> Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
* Error running Gradle:
ProcessException: Process "C:\flutter_projects\udacity-course\course\03_category_route\task_03_category_route\android\gradlew.bat" exited abnormally:

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#sec:command_line_warnings


FAILURE: Build failed with an exception.

* Where:
Build file 'C:\flutter_projects\udacity-course\course\03_category_route\task_03_category_route\android\build.gradle' line: 24

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
  Command: C:\flutter_projects\udacity-course\course\03_category_route\task_03_category_route\android\gradlew.bat app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.

>

**Comment by maryx** [comment]
Can you run it with '--warning-mode all' and paste your output here?

**Comment by aleksoft1** [comment]
> Can you run it with '--warning-mode all' and paste your output here?

Here you are:

> C:\flutter_projects\udacity-course\course\03_category_route\task_03_category_route>gradle --warning-mode all

> Task :help

Welcome to Gradle 5.2.1.

To run a build, run gradle <task> ...

To see a list of available tasks, run gradle tasks

To see a list of command-line options, run gradle --help

To see more detail about a task, run gradle help --task <task>

For troubleshooting, visit https://help.gradle.org

BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed

>

**Comment by maryx** [comment]
Oh, it seems like the flag actually had an `=` sign in it according to the docs here: https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#sec:command_line_warnings

So you'd want to try with `--warning-mode=all`

**Comment by aleksoft1** [comment]
> Oh, it seems like the flag actually had an `=` sign in it according to the docs here: https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#sec:command_line_warnings
> 
> So you'd want to try with `--warning-mode=all`

> C:\flutter_projects\udacity-course\course\03_category_route\task_03_category_route>gradle --warning-mode=all
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Task :help

Welcome to Gradle 5.2.1.

To run a build, run gradle <task> ...

To see a list of available tasks, run gradle tasks

To see a list of command-line options, run gradle --help

To see more detail about a task, run gradle help --task <task>

For troubleshooting, visit https://help.gradle.org

BUILD SUCCESSFUL in 7s
1 actionable task: 1 executed

C:\flutter_projects\udacity-course\course\03_category_route\task_03_category_route>gradle --status
   PID STATUS   INFO
 15548 IDLE     5.2.1
 13540 STOPPED  (by user or operating system)

Only Daemons for the current Gradle version are displayed. See https://docs.gradle.org/5.2.1/userguide/gradle_daemon.html#sec:status

>

**Comment by maryx** [comment]
It seems that the build was successful in this case^? Were you able to run the app in 3.0.1?

**Comment by aleksoft1** [comment]
> It seems that the build was successful in this case^? Were you able to run the app in 3.0.1?

Not yet. 
I think this status is for 5.2.1 :

> Only Daemons for the current Gradle version are displayed. See https://docs.gradle.org/5.2.1/userguide/gradle_daemon.html#sec:status

**Comment by maryx** [comment]
Can you get the error logs with `--warning-mode=all` for the 3.0.1 version? So we can see the cause of the error from your earlier comment (the `BUILD FAILED in 1s`)?

**Comment by maryx** [comment]
Also can you please post the output of `flutter doctor -v`? Thanks!

**Comment by aleksoft1** [comment]
From [Gradle releases page](https://gradle.org/releases/) I install version 3.0 (next version is v3.1). There is no command --warning-mode, but status is:

> C:\flutter_projects\udacity-course\course\03_category_route\task_03_category_route>gradle
:help                 

Welcome to Gradle 3.0.

To run a build, run gradle <task> ...

To see a list of available tasks, run gradle tasks

To see a list of command-line options, run gradle --help

To see more detail about a task, run gradle help --task <task>

BUILD SUCCESSFUL

Total time: 0.649 secs


> C:\flutter_projects\udacity-course\course\03_category_route\task_03_category_route>gradle --status
   PID STATUS   INFO  
 12168 IDLE     3.0
  4900 STOPPED  (by user or operating system)
 16368 STOPPED  (by user or operating system)

flutter doctor -v:

> C:\flutter_projects\udacity-course\course\03_category_route\task_03_category_route>flutter doctor -v
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.523], locale bg-BG)
    • Flutter version 1.0.0 at C:\src\flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\x\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.2
    • Flutter plugin version 32.0.3
    • Dart plugin version 183.5901

[√] VS Code (version 1.30.2)
    • VS Code at C:\Users\x\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.22.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

**Comment by maryx** [comment]
Ok, so it seems like you're able to build with 3.0 now. Is the build still failing for 3.0.1 for you?
Trying to figure out if there was a bad setup on your end or if all 3.0.1 builds are failing.

**Comment by aleksoft1** [comment]
Yes, I still have the same issue.

**Comment by maryx** [comment]
Oh, I see now.
It seems like maybe I am unable to replicate the issue because I'm on Linux/Mac while you're on Windows. So I'm not able to reproduce the `> No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android` error. See https://github.com/flutter/flutter/issues/22031 for more details.

Can you try this (https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#generated-project-files-outdated): "Delete the ios/ and android/ directories and run `flutter create .` to re-generate these directories." It essentially does what you did (bump up the gradle version).
This should unblock you for all the tasks in the course.

You'll also notice a lot of dependencies have changed too. Going to see what the best way to update all the course content would be...

**Comment by maryx** [comment]
Ok, so we're going to update all the projects in this repo by:
1) Removing `ios/` and `android/`
2) Running `flutter create .` This will update all dependencies.
3) Verify all the items that should be `.gitignore`ed are not committed.

Would you like to do this in your current PR or would you like me to do it (probably sometime tomorrow)?

**Comment by aleksoft1** [comment]
I prefer after update all projects I will clone repository again.

**Comment by maryx** [comment]
Ok, would you like me to update all the projects in this PR or make a separate PR?

**Comment by aleksoft1** [comment]
Better be ignor this PR and make a separate PR. Thank you for support!

**Comment by maryx** [comment]
Resolved in #158.

**Pull request closed without merging**
