### PR TITLE
Added Resources From Udacity Course

### PR DESCRIPTION
**Pull request by AdamMc331**
I really liked the list of resources that show up at the end of the course, and I went to reference them from the repository but noticed they weren't there (or I couldn't find them), so I just copy pasted the list from Udacity. I thought it would be helpful to have everything consolidated within the repo as well.

### CODE REVIEW

**Comment by AdamMc331** [comment]
I just signed the CLA! :)

**Comment by Hixie** [comment]
cc @maryx for review

**Comment by maryx** [comment]
This is a great idea! Can you add a link to `resources.md` inside the `README.md` too? You can make a new Resources header under all the existing Readme text and link to your file. Thanks!

**Comment by AdamMc331** [comment]
@maryx Thank you for the suggestion! I've added that, let me know what you think of the wording.

**Comment by maryx** [comment]
LGTM! Thanks for contributing!

**Pull request merged**
